apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-keycloak
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: nem-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: alertmanager-keycloak
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: secret/data/keycloak/alertmanager
        property: client_id
    - secretKey: client-secret
      remoteRef:
        key: secret/data/keycloak/alertmanager
        property: client_secret
