apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - alertmanager-configmap.yaml
  - alertmanager-externalsecret.yaml
  - alertmanager-serviceaccount.yaml
  - service.yaml
  - alertmanager-service.yaml
  - statefulset.yaml
  - alertmanager-statefulset.yaml
  - alertmanager-networkpolicy.yaml
  - sentinel-service-alias.yaml
  - sentinel-prometheus-egress.yaml
